apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: api-gateway
