apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 15672
      targetPort: 15672
    - name: queue
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: rabbitmq