kind: Service
apiVersion: v1
metadata:
  name: zuul-server
spec:
  selector:
    app: zuul-server
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-server
  labels:
    app: zuul-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-server
  template:
    metadata:
      labels:
        app: zuul-server
    spec:
      containers:
        - name: zuul-server
          image: ghcr.io/creative-hub-taass/zuul-proxy
          ports:
            - containerPort: 8080